package Workspace;


import Book.bookutil;
import CustomerOrder.cartutil;
import CustomerOrder.orderinfo;
import com.itextpdf.text.*;
import com.itextpdf.text.Font;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

import java.awt.*;
import java.io.File;
import java.io.FileOutputStream;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import static jdk.nashorn.internal.objects.NativeMath.round;

public class Pdf {

    private static String FILE = "FirstPdf.pdf";
    private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18,
            Font.BOLD);
    private static Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.NORMAL, BaseColor.RED);
    private static Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 16,
            Font.BOLD);
    private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.BOLD);

    public static void pdf(List<List<String>> Item , String branch,String month,String year) {
        try {
            Document document = new Document();
            FILE=branch+"_"+month+"_"+year+".pdf";
            PdfWriter.getInstance(document, new FileOutputStream(FILE));
            document.open();
            addMetaData(document);
            addTitlePage(document,branch,month,year,Item);

            document.close();
            Desktop.getDesktop().open(new File(FILE));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // iText allows to add metadata to the PDF which can be viewed in your Adobe
    // Reader
    // under File -> Properties
    private static void addMetaData(Document document) {
        document.addTitle("Report");
        document.addSubject("Book Report");
        document.addKeywords("book,order,purchase");
        document.addAuthor("XYZ Book Dot Com");
        document.addCreator("Latif Siddiq Sunny");
    }

    private static void addTitlePage(Document document,String branch,String month,String year, List<List<String>> Item )
            throws DocumentException {
        Paragraph preface = new Paragraph();
        addEmptyLine(preface, 1);
        preface.add(new Paragraph("Monthly Report", catFont));
        addEmptyLine(preface, 1);
        preface.add(new Paragraph(
                "Monthly report  for: " + branch,
                smallBold));


        // Will create: Report generated by: _name, _date
        preface.add(new Paragraph(
                "Report generated on: " +  new Date(),
                smallBold));
        preface.add(new Paragraph("Report on: "+month+","+year));
        addEmptyLine(preface, 3);

        PdfPTable table = new PdfPTable(5);

        // t.setBorderColor(BaseColor.GRAY);
        // t.setPadding(4);
        // t.setSpacing(4);
        // t.setBorderWidth(1);

        PdfPCell c1 = new PdfPCell(new Phrase("Serial Number"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Book Name"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Sold Price"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Buy Price"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Profit"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);
        table.setHeaderRows(1);
        int i=1;
        double sum=0;
        for(List<String> s: Item){
            table.addCell(String .valueOf(i));
int k=0;
            for(String x:s){
                // System.out.print(x+ " ");
                k++;
                table.addCell(x);
                if(k==4){
                    sum+=Double.valueOf(x);
                }

            }
            i++;
            //   System.out.println("");
        }


        table.addCell("");

        table.addCell("");
        table.addCell("");
        table.addCell("Total Profit");
        DecimalFormat df = new DecimalFormat("#.00");

        table.addCell(String .valueOf(df.format(sum)+" /-"));

        document.add(preface);
        document.add(table);

    }

    private static void addEmptyLine(Paragraph paragraph, int number) {
        for (int i = 0; i < number; i++) {
            paragraph.add(new Paragraph(" "));
        }
    }
}
